== Example

include::attributes.adoc[]

As mentioned above, the validator rules are all based on YAML format, {project-name} provides a bunch of built-in YAML tags to compose the expected result.
Here is an example of the `expected.yaml`:

[source,yaml]
.expected.yaml
----
include::{tagsdir}/src/test/resources/nn.v.yaml[tags=content,indent=0]
----
<1> The `name` must be `**n**ot **n**ull (!nn)`.
<2> The `age` must be `**g**reater **t**han (!gt) 12`, and the actual value is saved into a variable named `age` by `&age` syntax.
<3> The `height` must be `**l**ess **t**han (!lt) 200`.
<4> The `age` must be the same as the actual value in the first `student`.

NOTE: the exclamation mark `!` is NOT the same meaning as what it is in most programing languages, where it means `NOT`.
Instead, it's a notation in YAML indicating the following word is a {yaml-spec-tag-url}[tag], thus `!gt` means **greater than**, instead of **not greater than**, i.e. less than or equal to.

Let's see how to do the validation in Kotlin codes.

[source,kotlin]
.test.kt
----
include::{tagsdir}/src/test/kotlin/io/github/kezhenxu94/validators/TestTagProcessorNN.kt[tags=demo,indent=0]
----
<1> The `name` is `not null`.
<2> The `age` is `greater than 12`.
<3> The `age` is `equal to` the previous `age`.
<4> The missing field `height` is simply ignored.

And thus the validation passes.
